### ISSUE TITLE
idk whats happening bro😭

### ISSUE THREAD

**Issue by ccwang76** [XInTheDark/raycast-g4f#101]
i js typed in questions and the ai didnt reply, and an hour ago it was reply with "...chars generated" but nothing was appearing. on version 3.1

i might js be being stupid tho 

screen rec: https://www.dropbox.com/scl/fi/45grqqbulc0tlvpi4oyf7/Screen-Recording-2024-08-20-at-14.20.46.mov?rlkey=uehmlf0tlexjbtxne26e7b8vu&st=zfnjft0w&dl=0

**Comment by XInTheDark** [comment]
Hi, this occurs when the extension was unable to fetch any response from the provider. Can you show which provider you're using?
If it was previously working for you, then you might have hit some rate limit.
The best solution would be to change to a different provider, and see if it works. You can do this by selecting "Edit Chat Settings" (or pressing command-shift-O) and then choosing a different provider. You can also change your default provider if you wish to.

**Comment by ccwang76** [comment]
okay sorry im really slow, but whats a provider😭

**Comment by XInTheDark** [comment]
It's some third party website that the extension gets its results from. When you send a message, the extension is sending the message to that website/API behind the scenes, and then displaying the response returned to you.
