### ISSUE TITLE
Could not access GPT

### ISSUE THREAD

**Issue by isabhiii** [XInTheDark/raycast-g4f#104]
![SCR-20240826-mqrx](https://github.com/user-attachments/assets/39fcbd91-1f91-4cab-8ab2-ad7682d8f599)

I can't access the AI model even though I tried to use the different models. 
It was working completely fine yesterday. and Suddenly, today I encountered this bug.

**Note:** : I am not searching for anything inappropriate 😅

I am upto-date with the latest version of the extension.

**Comment by XInTheDark** [comment]
Hi, what provider are you using?
DeepInfra provider is down at the moment, so all its models don't work right now

**Comment by isabhiii** [comment]
Okay. I was using DeepInfra's models. Thank you for the info.
