### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by VaMPIRESqq** [XInTheDark/raycast-g4f#112]
`lse@redest ~/raycast-g4f (main)> npm ci; npm run dev;npm -v;node -v; uname -a
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, `which` is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.5.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@1.2.1: Use @eslint/object-schema instead

added 189 packages, and audited 190 packages in 6s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> raycast-g4f@3.4 dev
> ray develop

warn  -  Raycast is not running
info  -  entry points [src/askAI.jsx src/aiChat.jsx src/askAboutSelectedText.jsx src/askAboutScreenContent.jsx src/continue.jsx src/summarize.jsx src/explain.jsx src/fixCode.jsx src/friendly.jsx src/professional.jsx src/paraphrase.jsx src/synonyms.jsx src/translate.jsx src/improve.jsx src/longer.jsx src/shorter.jsx src/genImage.jsx src/customAICommands.jsx src/checkForUpdates.jsx src/configureLocalAPIs.jsx src/manageAIPresets.jsx]
failed streaming logs (exec: "log": cannot run executable found relative to current directory)
panic: failed streaming logs (exec: "log": cannot run executable found relative to current directory) [recovered]
	panic: failed streaming logs (exec: "log": cannot run executable found relative to current directory)

goroutine 34 [running]:
github.com/raycast/ray/errors.ExitMsg(...)
	/Users/runner/work/raycast-macos/raycast-macos/Commands/tools/ray/errors/errors.go:14
github.com/raycast/ray/cmd.readOSLogStream()
	/Users/runner/work/raycast-macos/raycast-macos/Commands/tools/ray/cmd/develop.go:268 +0x487
github.com/raycast/ray/cmd.watchLogs.func1.1()
	/Users/runner/work/raycast-macos/raycast-macos/Commands/tools/ray/cmd/develop.go:166 +0x2f
panic({0xba33a0?, 0xc0005131c0?})
	/Users/runner/hostedtoolcache/go/1.22.0/arm64/src/runtime/panic.go:770 +0x132
github.com/raycast/ray/errors.ExitMsg(...)
	/Users/runner/work/raycast-macos/raycast-macos/Commands/tools/ray/errors/errors.go:14
github.com/raycast/ray/cmd.readOSLogStream()
	/Users/runner/work/raycast-macos/raycast-macos/Commands/tools/ray/cmd/develop.go:268 +0x487
github.com/raycast/ray/cmd.watchLogs.func1()
	/Users/runner/work/raycast-macos/raycast-macos/Commands/tools/ray/cmd/develop.go:170 +0x35
created by github.com/raycast/ray/cmd.watchLogs in goroutine 1
	/Users/runner/work/raycast-macos/raycast-macos/Commands/tools/ray/cmd/develop.go:161 +0x1a
10.8.3
v22.8.0
Linux redest 6.10.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 15:16:37 +0000 x86_64 GNU/Linux
`

**Comment by XInTheDark** [comment]
hi, currently raycast-g4f is only available for macOS, since it's an extension for raycast (a mac-only app). I'm not sure if they will add Linux support in the future, but it's possible

**Comment by VaMPIRESqq** [comment]
> hi, currently raycast-g4f is only available for macOS, since it's an extension for raycast (a mac-only app). I'm not sure if they will add Linux support in the future, but it's possible

ooh, I didn't know, thank you very much
