### ISSUE TITLE
Cannot Create Images

### ISSUE THREAD

**Issue by SupremeRubisco** [XInTheDark/raycast-g4f#117]
**Description**
When I go to "Generate Images" and type in a prompt it will not generate anything.

**To Reproduce**
1. Go to 'Generate Images'
2. Enter any prompt, "I usually enter "car" or "generate an image of a car" for testing
3. I see the error, "GPT cannot process this prompt."

**Expected behavior**
It should generate an image.

**Screenshots/Recordings**
<img width="801" alt="Screenshot 2024-09-22 at 8 30 32 PM" src="https://github.com/user-attachments/assets/d1f677cd-e352-488d-a29d-64d773fd91c8">

**Information**
 - raycast-g4f version: v3.6
 - Raycast version: v1.83.0

**Additional context**
It has thrown this error ever since I updated to Sequoia the 2nd time after I downgraded.

**Comment by XInTheDark** [comment]
Hi! Have you tried selecting different providers to see if it's a provider issue?

**Comment by SupremeRubisco** [comment]
> Hi! Have you tried selecting different providers to see if it's a provider issue? You can do this by pressing Command+N and then choosing a different one from the dropdown.

Hello, just tried a different provider and it stills seems to be an issue. Do you have an idea what I could be?

**Comment by cdb97** [comment]
Having the same issue as of version 3.9.1 of the extension. Raycast version is 1.84.1

**Comment by kjenney** [comment]
I was only able to generate an image using Rocks. Every other provider gave me an error.

**Comment by XInTheDark** [comment]
Thanks for the feedback - I've identified the issue and will fix the image generation very soon!
