### ISSUE TITLE
Default Language prevails over text commands

### ISSUE THREAD

**Issue by aloshev** [XInTheDark/raycast-g4f#128]
**Describe the bug**
Commands may use Default Language, even if their instructions require a language based on context

**To Reproduce**
1. Open the Change Tone command
2. Enter text in a non-default language.

**Expected behavior**
Commands applicable in various language contexts should ignore Default Language 
Additionally, I would like the option to not specify a default language

**Screenshots/Recordings**

https://github.com/user-attachments/assets/d350afe6-40f6-4304-871c-088c1e5d0c0f

**Information**
 - raycast-g4f version: 3.9.1
 - Raycast version: 1.84.2
 - Provider: Blackbox (gpt-4o)

**Additional context**
Custom AI Commands are also affected

**Comment by XInTheDark** [comment]
Hi - thanks for the suggestion!
I will disable Default Language by default for most commands, and enable it only for the following:
- Summarize
- Explain

btw, if the default language is set to English, then the corresponding prompt will not be added

**Comment by XInTheDark** [comment]
Hi, can you check if the bug is fixed? thanks
