### ISSUE TITLE
Automatic update still not working

### ISSUE THREAD

**Issue by VegardNerland** [XInTheDark/raycast-g4f#129]
#@ Update failed! Error: Error: Command failed: sh update.sh
Log:
NPM executable is not valid!

Running 3.8.1. Everything else is up to date. Sequoia Beta 15.1

**Comment by XInTheDark** [comment]
Hi! Can you run the following commands
- `which npm`
- `where npm`
and send the output?

Thanks!

**Comment by VegardNerland** [comment]
Both commands return this:

❯ which npm
/opt/homebrew/bin/npm
❯ where npm
/opt/homebrew/bin/npm

**Comment by XInTheDark** [comment]
Hey, this bug has been fixed in v3.9.1, so I suggest manually upgrading to it. Future automatic updates should work :)
