### ISSUE TITLE
[Feature] auto bind `Google  Gemini model` with `Ask About Screen Content` command

### ISSUE THREAD

**Issue by lovejavaee** [XInTheDark/raycast-g4f#140]
Only the `Google Gemini` model currently supports the `Ask About Screen Content` command. It is advisable to automatically bind `Google Gemini` to this command if the Google Gemini API Keys are set, regardless of the Default Provider.

Currently, to use `Ask About Screen Content`, I need to set the Default Provider to `Google Gemini`, but I prefer to use `Google Gemini` only for this command and keep other commands with different providers.

**Comment by XInTheDark** [comment]
hey, just implemented this feature - hope it works :)
