### ISSUE TITLE
Installation error - Build failed

### ISSUE THREAD

**Issue by rSaita** [XInTheDark/raycast-g4f#150]
Hi,
I get this error when trying to install. Please advise.

<img width="639" alt="Raycast-g4f error" src="https://github.com/user-attachments/assets/f52bf8d1-362d-4cdb-b24a-6c18d5694233">

**Comment by zcs19960929** [comment]
The same problem occurred after updating the code today. There is no problem using version v4.2.1 releases

**Comment by XInTheDark** [comment]
@rSaita @zcs19960929 Hi, thank you for reporting the issue! I have pushed the fix. It was because of a missing module that was not listed in the dependencies. I have made the dependency optional.

**Comment by XInTheDark** [comment]
can you check if the latest commit version works?

**Comment by zcs19960929** [comment]
> can you check if the latest commit version works?

![image](https://github.com/user-attachments/assets/228ebe1f-7a16-45ff-9638-30da5c0936bf)
![image](https://github.com/user-attachments/assets/7725133f-9699-4111-ac78-5d73a0c1c8ac)
It’s working properly now. Drawing can also be used normally.
thanks

**Comment by rSaita** [comment]
Everything works perfectly, thank you very much!


<img width="740" alt="cats" src="https://github.com/user-attachments/assets/a14015df-052b-458a-b3fd-1a0e220e5016">
