### ISSUE TITLE
Brand new installating - Nothing is working :(

### ISSUE THREAD

**Issue by PatDal81** [XInTheDark/raycast-g4f#157]
**Describe the bug**
Fresh install, plugin appears in Raycast but when using any model, the cursor just spins and nothing happens (Response loading).  Getting the error "undefined char, undefined / sec" after a few seconds.  I left the npm terminal window open and got the following error, if it helps:

15:30:03.412 Key: chatData not found, returning default value
15:30:03.412 Key: AIPresets not found, returning default value
15:30:03.412 Key: chatData not found, returning default value
15:30:03.412 Key: AIPresets not found, returning default value
15:30:03.412 Pruned 0 stored chats
15:30:03.416 Pruned 0 stored chats
15:31:33.569 Key: lastPruneChatsTime not found, returning default value
15:31:33.569 Storage API: Warning: value for key lastPruneChatsTime is not a string

**To Reproduce**
Tried with "ask question" and "AI Chat" extensively, same behaviour.  

**Expected behavior**
Expect it to work :)

**Screenshots/Recordings**
If applicable, add screenshots or screen recordings to help explain your problem.

**Information**
 - raycast-g4f version: latest version (4.3)
 - Raycast version: latest version (1.86)

**Additional context**
Tried uninstalling and reinstalling, simply don't understand what I'm doing wrong.  Do I have to keep npm running in the background?

**Comment by XInTheDark** [comment]
Hi, could you try switching to a different provider? Sometimes some third party providers don't work and such issues may happen.

**Comment by PatDal81** [comment]
Hi, I've tried multiple providers without any success.  They all give me the same issue (same behavior).

**Comment by PatDal81** [comment]
You mean in the extension preferences, right?  I just tried switching it in the chat setting and it seem to be working now.  Is this expected?

**Comment by XInTheDark** [comment]
Hi! Glad to hear that a provider is working!
When you change the default provider in the extension preferences, you'll need to create a new chat for the change to take effect - the previous chats' providers remain the same, since providers can be changed on a per-chat basis.

**Comment by PatDal81** [comment]
Got it!  Don't think it's already documented but I can see value in having this written down somewhere.  I think that, in my case, the default provider stopped working and it made the whole experience bad from the start.  I now use Duckduckgo as the provider and it works well.

**Comment by PatDal81** [comment]
Awesome, thanks for the update on this!
