### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Riemannb** [XInTheDark/raycast-g4f#160]
The following problem occurred a few days ago. 

**Screenshots**
<img width="769" alt="image" src="https://github.com/user-attachments/assets/049cdb23-3412-40c2-88b5-a44370ab8465">
<img width="776" alt="image" src="https://github.com/user-attachments/assets/844fab73-65c1-4ed3-9242-8f49618a0569">

**Information**
 - raycast-g4f version: 4.3

The problem disappears after reinstallation, but has come back once before. What do you recommend to do next time?

**Comment by XInTheDark** [comment]
Thanks for reporting the bug!

I've addressed this in the latest commit, and it will be included in the next release
