### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by lavalogy-Cloud** [XInTheDark/raycast-g4f#162]
Does this extension work on mac if so can you instruct me as to how to install if not can maybe change that in the future

**Comment by XInTheDark** [comment]
Hi! Yes, the extension works on Mac - and only on Mac, as of now :)
First you will need to download the Raycast app at https://www.raycast.com/. Then follow the installation instructions.
I'll also be updating the README to make this clearer - thanks for opening an issue!
