### ISSUE TITLE
Proofread option

### ISSUE THREAD

**Issue by isabhiii** [XInTheDark/raycast-g4f#164]
- there is an option to "Improve Writing" but not for the 'Proofread / Grammar check'. Please make it possible.
- And if you can add an option to use the 'AI Presets' as other options, use them directly like Improve writing, AI chat,.. it would be great. PIN them and then use them as other AI presets outside of the 'Manage AI Preset' option.

Thank you !

**Comment by XInTheDark** [comment]
Hi! To add a new command, you could create it in Custom AI Commands with any prompt you like.

> * And if you can add an option to use the 'AI Presets' as other options, use them directly like Improve writing, AI chat,.. it would be great. PIN them and then use them as other AI presets outside of the 'Manage AI Preset' option.

Thanks for the suggestion - I am planning to rework the way providers & presets are managed. After the rework this should be possible.

**Comment by isabhiii** [comment]
Hi! Thank you for the response. I've already created some custom AI commands, but accessing them is a hassle. Thanks for the update on this!

**Comment by XInTheDark** [comment]
Hi! I'd like to apologize for the custom AI commands being difficult to access - it's a Raycast limitation that extensions cannot add or modify its own commands.
If you'd still like to create your own extension command, you can do it by manually modifying the source code. In particular `package.json` defines the commands while the respective `.jsx` files define the respective prompts. I'll post a guide on this soon.

**Comment by isabhiii** [comment]
Hi! Thank you. Waiting for the guide.

**Comment by abdcef** [comment]
I have a similar request to create a default prompt for Proofread / Grammar checks. I tried the attached but it does not seem to work for the selected text. Appreciate any suggestion on making this work till a default option is made available

![Image](https://github.com/user-attachments/assets/e6e5643e-738d-4e73-980f-31023d1251b1)

![Image](https://github.com/user-attachments/assets/54b032cf-e918-4bfa-9a5d-faf7833b2de8)

**Comment by isabhiii** [comment]
There is an option called 'Format Text' that checks the grammar of selected text. It is in the default commands of this extension. look up for it.

<img width="770" alt="Image" src="https://github.com/user-attachments/assets/83391405-53f2-4f88-a289-8c80e7429329" />
