### ISSUE TITLE
Google Gemini API Key Error

### ISSUE THREAD

**Issue by lovejavaee** [XInTheDark/raycast-g4f#172]
**Describe the bug**
Can not able to add Google Gemini API KEY

**To Reproduce**
1. Go to `Preferences`
2. Click on `[Manage APis] Google Gemini`
3. Add Google Gemini API KEY
4. Click `Save` button, nothing happen

**Expected behavior**
Able to add Google Gemini API KEY as expect

**Information**
 - raycast-g4f version: [e.g. v5.0]
 - Raycast version: [e.g. v1.88.4]

**Comment by XInTheDark** [comment]
Hi - the save action is missing a visual confirmation, though it is saving the key correctly. I'll patch this in the next release.
