### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by NyxAltair** [XInTheDark/raycast-g4f#26]
![image](https://github.com/XInTheDark/raycast-g4f/assets/170422885/ea9bca6e-98d5-40b3-b124-99af41acfb2f)

when i build npm run build throw error like that.

**Comment by NyxAltair** [comment]
im using windows with vscode and powershell as terminal

**Comment by XInTheDark** [comment]
Thank you for reporting the issue!
Can you run
1. `npm ci`, then
2. run `npm run build` again?

**Comment by NyxAltair** [comment]
still error, got hint this repo using ray.
just check ur docs and realize this using ray, nvm i use windows
so maybe i will check later on my linux
thnks for your fast respon, i appreciate
