### ISSUE TITLE
AI Chat throws an error

### ISSUE THREAD

**Issue by DanTimu** [XInTheDark/raycast-g4f#46]
Hi, when trying to use AI Chat I get the following error: TypeError: Cannot read properties of undefined (reading 'messages')
<img width="862" alt="Screenshot 2024-06-13 at 23 10 15" src="https://github.com/XInTheDark/raycast-g4f/assets/4921546/01ed42a4-6acb-45b1-9b50-a7bb35212041">

**Comment by XInTheDark** [comment]
Hi! Could you provide the following details:
- Does the issue occur immediately upon starting AI Chat?
- Does the issue occur with latest version of the extension?

Additionally, can you try to apply the following fixes:
1. Update the extension to the latest version;
2. If the issue still persists, launch any other AI command and choose "Clear Local Storage & Cache" at the bottom of the actions list.

Thanks!

**Comment by DanTimu** [comment]
Hi,

- I type ai chat and tab and it shows me the error.
- Latest version installed (1.2)
- Did Clear Assets Cache + Clear Local Storage & Cache


https://github.com/XInTheDark/raycast-g4f/assets/4921546/4c6d6b1f-012d-41a6-89e8-ee5b678240a2

**Comment by DanTimu** [comment]
Hi, thanks. I uninstalled and installed the extension again and it worked.
