### ISSUE TITLE
Ask about screen content opens up Query input box

### ISSUE THREAD

**Issue by binaryblitz10** [XInTheDark/raycast-g4f#50]
Using the command "Ask About Screen Content" takes me to the query box as shown below

![Screenshot 2024-06-20 at 07 31 59 PM](https://github.com/XInTheDark/raycast-g4f/assets/169087053/0da5b4e2-6080-465b-a05c-b06d0f7a488c)

**Comment by XInTheDark** [comment]
Hi! This is expected behaviour, as it allows the user to input a query alongside the screenshot.

**Comment by binaryblitz10** [comment]
Hi! Thank you for letting me know.

However, it is not sending the screenshot.

**Comment by XInTheDark** [comment]
Could you post a clip of the command usage to show the problem? Thanks.

**Comment by binaryblitz10** [comment]
Sure, here you go:


https://github.com/XInTheDark/raycast-g4f/assets/169087053/090f3799-9637-42c0-929f-66473f4ae690

**Comment by XInTheDark** [comment]
Hi! Could you do the following:
1. navigate to some directory (e.g. Documents)
2. check whether the command `/usr/sbin/screencapture screenshot.png` succeeds, i.e. whether it will save a screenshot into the directory.
Thanks.

**Comment by binaryblitz10** [comment]
Hey! Yes, that did work. It did create screenshot.png in that folder.

**Comment by XInTheDark** [comment]
Hmm, have you tried asking different queries relating to the image to confirm that it wasn't uploaded?

Lastly, if it's indeed not working, could you select "Continue in Chat" and check whether a metadata section exists that says "Files", followed by a file path to the screenshot?

**Comment by XInTheDark** [comment]
Hi! I think the problem should be with your provider selection - currently only the Google Gemini provider supports file/image uploads, and by extension, the "Ask about screen content" command. Hope this helps!

**Comment by binaryblitz10** [comment]
Oh that must be it then. I have GPT4 selected as default and see that Gemini requires API keys.
