### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by RihardsVeters** [XInTheDark/raycast-g4f#75]
I'm unable to install this extension, i get this error.
![CleanShot 2024-07-26 at 16 00 10@2x](https://github.com/user-attachments/assets/6921dae7-b781-4417-a0bd-c4af7c579462)

**Comment by JohnnWi** [comment]
i have same problem

**Comment by XInTheDark** [comment]
Hi! According to the [Raycast documentation[(https://developers.raycast.com/basics/getting-started) you need to be signed in to Raycast, in order to install extensions locally. Can you check if you're signed in?
