### ISSUE TITLE
Add option to config the ollama server address

### ISSUE THREAD

**Issue by livelazily** [XInTheDark/raycast-g4f#84]
**Is your feature request related to a problem? Please describe.**
I hav a powerfule server on lan to run ollama, I wan to use it instead runing ollama on locale

**Describe the solution you'd like**
Just add option to set the ollama server address

**Describe alternatives you've considered**

**Additional context**

**Comment by XInTheDark** [comment]
thanks for the suggestion! will implement really soon!

**Comment by XInTheDark** [comment]
@livelazily Added in v2.7.1, could you check if it works properly?

**Comment by livelazily** [comment]
It's running smoothly, but I suggest adding a refresh button after the model settings, so that the model list can be refreshed immediately after changing the address. This way, there's no need to save the address and then re-enter the settings to select the model.

**Comment by XInTheDark** [comment]
Ok, I have just removed the behavior where the command closes after saving settings. You can now simply do `Command-R` (or select "Reload" in the actions) to refresh the page.

**Comment by livelazily** [comment]
The `Command+R` method is not very intuitive.
I suggest add a onBlur event on `ollama_api`, call the "new" api address to update the `ollama_model` values if success, when user leave the api field.
I'm not very familiar with React, otherwise I would like to submit a pull request directly😅.

**Comment by XInTheDark** [comment]
Thank you, I added it in the latest commit https://github.com/XInTheDark/raycast-g4f/commit/61af38e57665b5b21a9268e153b7ac39c3e0c900
