### ISSUE TITLE
How to set translation preferences to Chinese

### ISSUE THREAD

**Issue by shawokou123** [XInTheDark/raycast-g4f#89]
When I run this tool and want to translate English web content into Chinese.
The preference is "english," how to set the preference to "Chinese"

<img width="610" alt="4b71b0320f9e566ecc52bc3b5" src="https://github.com/user-attachments/assets/33388285-7590-4b92-ac0e-a2a1887aea6e">

**Comment by XInTheDark** [comment]
Hi! Thanks for the feature request. I will implement some improvements that make it easier to translate to your preferred language.

**Comment by XInTheDark** [comment]
@shawokou123 Hi! I've added the feature so that the command defaults to using the previously selected language. It has been released in [v2.10](https://github.com/XInTheDark/raycast-g4f/releases/tag/v2.10). Does this resolve your issue?
