### ISSUE TITLE
Unable to change default model

### ISSUE THREAD

**Issue by hmseeb** [XInTheDark/raycast-g4f#93]
**Bug Description**  
After changing the default model in the settings from `gpt-3.5` to `gpt-4o-mini`, I asked the model "Who are you?" and it responded as `gpt-3.5`.

**Steps to Reproduce**  
1. Go to the settings.
2. Change the model to `get-4o-mini`.
3. Use the "Ask AI" command.
4. Enter your query.
5. The response will be from `gpt-3.5` instead of the selected model.

**Comment by XInTheDark** [comment]
Hi, I'm unable to reproduce the bug - could you provide a screen recording to show the problem? Thanks.
