### ISSUE TITLE
Error Generate Images 

### ISSUE THREAD

**Issue by tickernelz** [XInTheDark/raycast-g4f#94]
**Describe the bug**
i can't open generate image, the error you can see below

**To Reproduce**
1. Go to 'Raycast'
2. Click on 'Generate Images'
3. See error

**Screenshots/Recordings**
![CleanShot 2024-08-15 at 16 42 57](https://github.com/user-attachments/assets/69a92756-ef1e-44bb-bc3c-0e2f155bf2e8)

**Information**
 - raycast-g4f version: v3.0
 - Raycast version: v1.79.1

**Comment by XInTheDark** [comment]
Hi! Could you run the "Clear Local Storage & Cache" action from any other command, and see if this resolves the issue?

**Comment by tickernelz** [comment]
> Hi! Could you run the "Clear Local Storage & Cache" action from any other command, and see if this resolves the issue?

how can i do that? in raycast i didn't find it

**Comment by XInTheDark** [comment]
> > Hi! Could you run the "Clear Local Storage & Cache" action from any other command, and see if this resolves the issue?
> 
> how can i do that? in raycast i didn't find it

You can run any command, for example "Ask AI", and then here you can choose the action:

<img width="774" alt="Screenshot 2024-08-15 at 21 27 56" src="https://github.com/user-attachments/assets/cd5cf1a9-4894-4ee8-8ebd-34b1f784b929">

**Comment by tickernelz** [comment]
> > > Hi! Could you run the "Clear Local Storage & Cache" action from any other command, and see if this resolves the issue?
> > 
> > 
> > how can i do that? in raycast i didn't find it
> 
> You can run any command, for example "Ask AI", and then here you can choose the action:
> 
> <img alt="Screenshot 2024-08-15 at 21 27 56" width="774" src="https://private-user-images.githubusercontent.com/61100393/358233015-cd5cf1a9-4894-4ee8-8ebd-34b1f784b929.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mjg3OTQsIm5iZiI6MTcyMzcyODQ5NCwicGF0aCI6Ii82MTEwMDM5My8zNTgyMzMwMTUtY2Q1Y2YxYTktNDg5NC00ZWU4LThlYmQtMzRiMWY3ODRiOTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEzMjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZGRlOTA2MmVmODhhMjdhODE4ZDgwNDM0NWVlNGYyOTljMmQ3YmYwMGYwZmMzNTE1ZTE4Njg1MGI5Y2QyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZiuvWUdfA24CNuJdsedV_G0J4QS5AaO83avnBVlGcfs">

after i did that, the error still come out
